version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5054
      - ConnectionString=server=host.docker.internal;port=5432;database=store;uid=postgres;password=${PASSWORD};
    depends_on:
      - postgres
    ports:
      - 5054:5054
  
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: store
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4